# Generated by Django 4.0.10 on 2023-02-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_shell', '0002_islam_languages_programming_psychology_sciences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadSciencesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadsciencesitem', to='book_shell.profile')),
                ('sciences_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sciences_items', to='book_shell.sciences')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadPsychologyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadpsychologyitem', to='book_shell.profile')),
                ('psychology_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychology_items', to='book_shell.psychology')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadProgrammingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadprogrammingitem', to='book_shell.profile')),
                ('programming_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_items', to='book_shell.programming')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadMystry_and_PoliceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('mystry_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mystry_items', to='book_shell.mystry_and_police')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadmystry_and_policeitem', to='book_shell.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLanguagesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('languages_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_items', to='book_shell.languages')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadlanguagesitem', to='book_shell.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadIslamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('islam_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='islam_items', to='book_shell.islam')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadislamitem', to='book_shell.profile')),
            ],
        ),
    ]
