# Generated by Django 4.0.10 on 2023-03-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0003_profile_downloadsciencesitem_downloadpsychologyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='islam',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='languages',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mystry_and_police',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='programming',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='psychology',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sciences',
            name='story',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
