# Generated by Django 4.0.10 on 2023-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0004_islam_story_languages_story_mystry_and_police_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islam',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mystry_and_police',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programming',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sciences',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
