# Generated by Django 4.0.10 on 2023-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0005_alter_islam_story_alter_languages_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='islam',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='languages',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='mystry_and_police',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='programming',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='psychology',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='sciences',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
