# Generated by Django 4.0.10 on 2023-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0008_report_issue_add_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='informention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mystry_and_police',
            name='informention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programming',
            name='informention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psychology',
            name='informention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sciences',
            name='informention',
            field=models.TextField(blank=True),
        ),
    ]
