# Generated by Django 4.0.10 on 2023-06-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0010_rename_informention_languages_information_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sciences',
            new_name='Science',
        ),
    ]
